<a href="https://colab.research.google.com/github/vikassinngh123/AI-ML-Learning/blob/main/04-Pandas/01_Chips_Experimental_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
chips=pd.read_csv("/content/drive/MyDrive/chips.csv")
chips

          Day Chips_Type  Unit_Sold
0      Monday       Lays         25
1      Monday    Takatak         15
2     Tuesday       Lays         10
3     Tuesday    Takatak         20
4   Wednesday       Lays         15
5   Wednesday    Takatak         10
6    Thursday       Lays          5
7    Thursday    Takatak         20
8      Friday       Lays         15
9      Friday    Takatak         15
10   Saturday       Lays         35
11   Saturday    Takatak         25
12     Sunday       Lays         45
13     Sunday    Takatak         40

In [3]:
chips.shape

(14, 3)

In [4]:
chips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Day         14 non-null     object
 1   Chips_Type  14 non-null     object
 2   Unit_Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes

In [5]:
chips.head()

         Day Chips_Type  Unit_Sold
0     Monday       Lays         25
1     Monday    Takatak         15
2    Tuesday       Lays         10
3    Tuesday    Takatak         20
4  Wednesday       Lays         15

In [6]:
chips.tail()

         Day Chips_Type  Unit_Sold
9     Friday    Takatak         15
10  Saturday       Lays         35
11  Saturday    Takatak         25
12    Sunday       Lays         45
13    Sunday    Takatak         40

In [7]:
chips.describe()

       Unit_Sold
count  14.000000
mean   21.071429
std    11.796116
min     5.000000
25%    15.000000
50%    17.500000
75%    25.000000
max    45.000000

In [8]:
chips['Prize_INR']=np.where(chips['Chips_Type']=='Lays',20,10)
chips.head()

         Day Chips_Type  Unit_Sold  Prize_INR
0     Monday       Lays         25         20
1     Monday    Takatak         15         10
2    Tuesday       Lays         10         20
3    Tuesday    Takatak         20         10
4  Wednesday       Lays         15         20

In [9]:
# chips.drop(0)
chips.drop(columns=['Prize_INR'])
# chips.drop(columns=['Prize ₹'], inplace=True) -> will remove the columns from data completely

          Day Chips_Type  Unit_Sold
0      Monday       Lays         25
1      Monday    Takatak         15
2     Tuesday       Lays         10
3     Tuesday    Takatak         20
4   Wednesday       Lays         15
5   Wednesday    Takatak         10
6    Thursday       Lays          5
7    Thursday    Takatak         20
8      Friday       Lays         15
9      Friday    Takatak         15
10   Saturday       Lays         35
11   Saturday    Takatak         25
12     Sunday       Lays         45
13     Sunday    Takatak         40

In [10]:
chips #-> still has 'Prize_INR' as inplace is false by defaults

          Day Chips_Type  Unit_Sold  Prize_INR
0      Monday       Lays         25         20
1      Monday    Takatak         15         10
2     Tuesday       Lays         10         20
3     Tuesday    Takatak         20         10
4   Wednesday       Lays         15         20
5   Wednesday    Takatak         10         10
6    Thursday       Lays          5         20
7    Thursday    Takatak         20         10
8      Friday       Lays         15         20
9      Friday    Takatak         15         10
10   Saturday       Lays         35         20
11   Saturday    Takatak         25         10
12     Sunday       Lays         45         20
13     Sunday    Takatak         40         10

In [11]:
chips['Revenue']=chips['Unit_Sold']*chips['Prize_INR']
chips

          Day Chips_Type  Unit_Sold  Prize_INR  Revenue
0      Monday       Lays         25         20      500
1      Monday    Takatak         15         10      150
2     Tuesday       Lays         10         20      200
3     Tuesday    Takatak         20         10      200
4   Wednesday       Lays         15         20      300
5   Wednesday    Takatak         10         10      100
6    Thursday       Lays          5         20      100
7    Thursday    Takatak         20         10      200
8      Friday       Lays         15         20      300
9      Friday    Takatak         15         10      150
10   Saturday       Lays         35         20      700
11   Saturday    Takatak         25         10      250
12     Sunday       Lays         45         20      900
13     Sunday    Takatak         40         10      400

In [12]:
chips.groupby('Day')

In [13]:
chips.set_index(['Day','Chips_Type','Unit_Sold','Prize_INR','Revenue'])

Empty DataFrame
Columns: []
Index: [(Monday, Lays, 25, 20, 500), (Monday, Takatak, 15, 10, 150), (Tuesday, Lays, 10, 20, 200), (Tuesday, Takatak, 20, 10, 200), (Wednesday, Lays, 15, 20, 300), (Wednesday, Takatak, 10, 10, 100), (Thursday, Lays, 5, 20, 100), (Thursday, Takatak, 20, 10, 200), (Friday, Lays, 15, 20, 300), (Friday, Takatak, 15, 10, 150), (Saturday, Lays, 35, 20, 700), (Saturday, Takatak, 25, 10, 250), (Sunday, Lays, 45, 20, 900), (Sunday, Takatak, 40, 10, 400)]

In [14]:
chips['COC']=np.where(chips['Chips_Type']=="Lays",17,8)
#  Here COC means cost on company per bag of chips like a 20 rs chips cost 17 rs to the company
chips

          Day Chips_Type  Unit_Sold  Prize_INR  Revenue  COC
0      Monday       Lays         25         20      500   17
1      Monday    Takatak         15         10      150    8
2     Tuesday       Lays         10         20      200   17
3     Tuesday    Takatak         20         10      200    8
4   Wednesday       Lays         15         20      300   17
5   Wednesday    Takatak         10         10      100    8
6    Thursday       Lays          5         20      100   17
7    Thursday    Takatak         20         10      200    8
8      Friday       Lays         15         20      300   17
9      Friday    Takatak         15         10      150    8
10   Saturday       Lays         35         20      700   17
11   Saturday    Takatak         25         10      250    8
12     Sunday       Lays         45         20      900   17
13     Sunday    Takatak         40         10      400    8

In [15]:
chips.drop(columns='Revenue',inplace=True)

In [16]:
chips['Sales']=chips['Prize_INR']*chips['Unit_Sold']
chips

          Day Chips_Type  Unit_Sold  Prize_INR  COC  Sales
0      Monday       Lays         25         20   17    500
1      Monday    Takatak         15         10    8    150
2     Tuesday       Lays         10         20   17    200
3     Tuesday    Takatak         20         10    8    200
4   Wednesday       Lays         15         20   17    300
5   Wednesday    Takatak         10         10    8    100
6    Thursday       Lays          5         20   17    100
7    Thursday    Takatak         20         10    8    200
8      Friday       Lays         15         20   17    300
9      Friday    Takatak         15         10    8    150
10   Saturday       Lays         35         20   17    700
11   Saturday    Takatak         25         10    8    250
12     Sunday       Lays         45         20   17    900
13     Sunday    Takatak         40         10    8    400

In [17]:
chips['Profit']=(chips['Prize_INR']-chips['COC'])*chips['Unit_Sold']
chips

          Day Chips_Type  Unit_Sold  Prize_INR  COC  Sales  Profit
0      Monday       Lays         25         20   17    500      75
1      Monday    Takatak         15         10    8    150      30
2     Tuesday       Lays         10         20   17    200      30
3     Tuesday    Takatak         20         10    8    200      40
4   Wednesday       Lays         15         20   17    300      45
5   Wednesday    Takatak         10         10    8    100      20
6    Thursday       Lays          5         20   17    100      15
7    Thursday    Takatak         20         10    8    200      40
8      Friday       Lays         15         20   17    300      45
9      Friday    Takatak         15         10    8    150      30
10   Saturday       Lays         35         20   17    700     105
11   Saturday    Takatak         25         10    8    250      50
12     Sunday       Lays         45         20   17    900     135
13     Sunday    Takatak         40         10    8    400      80

In [18]:
chips.drop(columns=['Profit'],inplace=True)

In [19]:
chips.groupby(chips['Chips_Type'])['Unit_Sold'].sum()

Chips_Type
Lays       150
Takatak    145
Name: Unit_Sold, dtype: int64

In [20]:
chips.groupby(['Chips_Type']).agg({'Unit_Sold' : 'sum' , 'Sales' : 'sum'}).reset_index()

  Chips_Type  Unit_Sold  Sales
0       Lays        150   3000
1    Takatak        145   1450

In [21]:
pivot = chips.pivot(columns='Chips_Type',index='Day',values='Sales')
pivot

Chips_Type  Lays  Takatak
Day
Friday       300      150
Monday       500      150
Saturday     700      250
Sunday       900      400
Thursday     100      200
Tuesday      200      200
Wednesday    300      100

In [22]:
chips['Yesterday_Sales']=chips['Sales'].shift(2)
chips['Yesterday_Sales'].fillna(0,inplace=True)
chips

/tmp/ipykernel_53026/3796547882.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  chips['Yesterday_Sales'].fillna(0,inplace=True)

          Day Chips_Type  Unit_Sold  Prize_INR  COC  Sales  Yesterday_Sales
0      Monday       Lays         25         20   17    500              0.0
1      Monday    Takatak         15         10    8    150              0.0
2     Tuesday       Lays         10         20   17    200            500.0
3     Tuesday    Takatak         20         10    8    200            150.0
4   Wednesday       Lays         15         20   17    300            200.0
5   Wednesday    Takatak         10         10    8    100            200.0
6    Thursday       Lays          5         20   17    100            300.0
7    Thursday    Takatak         20         10    8    200            100.0
8      Friday       Lays         15         20   17    300            100.0
9      Friday    Takatak         15         10    8    150            200.0
10   Saturday       Lays         35         20   17    700            300.0
11   Saturday    Takatak         25         10    8    250            150.0
12     Sunday       Lays         45         20   17    900            700.0
13     Sunday    Takatak         40         10    8    400            250.0

In [23]:
chips['%_change']=chips['Sales']/chips['Yesterday_Sales'] *100
chips

,Day,Chips_Type,Unit_Sold,Prize_INR,COC,Sales,Yesterday_Sales,%_change
0,Monday,Lays,25,20,17,500,0.0,inf
1,Monday,Takatak,15,10,8,150,0.0,inf
2,Tuesday,Lays,10,20,17,200,500.0,40.000000
3,Tuesday,Takatak,20,10,8,200,150.0,133.333333
4,Wednesday,Lays,15,20,17,300,200.0,150.000000
5,Wednesday,Takatak,10,10,8,100,200.0,50.000000
6,Thursday,Lays,5,20,17,100,300.0,33.333333
7,Thursday,Takatak,20,10,8,200,100.0,200.000000
8,Friday,Lays,15,20,17,300,100.0,300.000000
9,Friday,Takatak,15,10,8,150,200.0,75.000000
10,Saturday,Lays,35,20,17,700,300.0,233.333333
11,Saturday,Takatak,25,10,8,250,150.0,166.666667
12,Sunday,Lays,45,20,17,900,700.0,128.571429
13,Sunday,Takatak,40,10,8,400,250.0,160.000000

In [24]:
chips['UnitSold_Rank']=chips['Unit_Sold'].rank(method='first',ascending=False)
chips.sort_values(['UnitSold_Rank'])

,Day,Chips_Type,Unit_Sold,Prize_INR,COC,Sales,Yesterday_Sales,%_change,UnitSold_Rank
12,Sunday,Lays,45,20,17,900,700.0,128.571429,1.0
13,Sunday,Takatak,40,10,8,400,250.0,160.000000,2.0
10,Saturday,Lays,35,20,17,700,300.0,233.333333,3.0
0,Monday,Lays,25,20,17,500,0.0,inf,4.0
11,Saturday,Takatak,25,10,8,250,150.0,166.666667,5.0
3,Tuesday,Takatak,20,10,8,200,150.0,133.333333,6.0
7,Thursday,Takatak,20,10,8,200,100.0,200.000000,7.0
1,Monday,Takatak,15,10,8,150,0.0,inf,8.0
4,Wednesday,Lays,15,20,17,300,200.0,150.000000,9.0
8,Friday,Lays,15,20,17,300,100.0,300.000000,10.0
9,Friday,Takatak,15,10,8,150,200.0,75.000000,11.0
2,Tuesday,Lays,10,20,17,200,500.0,40.000000,12.0
5,Wednesday,Takatak,10,10,8,100,200.0,50.000000,13.0
6,Thursday,Lays,5,20,17,100,300.0,33.333333,14.0

In [25]:
chips['cumulative_sales']=chips['Sales'].cumsum()
chips

,Day,Chips_Type,Unit_Sold,Prize_INR,COC,Sales,Yesterday_Sales,%_change,UnitSold_Rank,cumulative_sales
0,Monday,Lays,25,20,17,500,0.0,inf,4.0,500
1,Monday,Takatak,15,10,8,150,0.0,inf,8.0,650
2,Tuesday,Lays,10,20,17,200,500.0,40.000000,12.0,850
3,Tuesday,Takatak,20,10,8,200,150.0,133.333333,6.0,1050
4,Wednesday,Lays,15,20,17,300,200.0,150.000000,9.0,1350
5,Wednesday,Takatak,10,10,8,100,200.0,50.000000,13.0,1450
6,Thursday,Lays,5,20,17,100,300.0,33.333333,14.0,1550
7,Thursday,Takatak,20,10,8,200,100.0,200.000000,7.0,1750
8,Friday,Lays,15,20,17,300,100.0,300.000000,10.0,2050
9,Friday,Takatak,15,10,8,150,200.0,75.000000,11.0,2200
10,Saturday,Lays,35,20,17,700,300.0,233.333333,3.0,2900
11,Saturday,Takatak,25,10,8,250,150.0,166.666667,5.0,3150
12,Sunday,Lays,45,20,17,900,700.0,128.571429,1.0,4050
13,Sunday,Takatak,40,10,8,400,250.0,160.000000,2.0,4450

In [26]:
# .rolling() for like 3 days
lays=chips[chips['Chips_Type']=="Lays"].copy()
lays['3day']=lays['Sales'].rolling(3).sum()
lays
#  lays dataframes have only one day while in chips same day repeasts 2 times
#  so if same thing used in chips it will not give the '3days' data but strat suming after 3 columns

,Day,Chips_Type,Unit_Sold,Prize_INR,COC,Sales,Yesterday_Sales,%_change,UnitSold_Rank,cumulative_sales,3day
0,Monday,Lays,25,20,17,500,0.0,inf,4.0,500,NaN
2,Tuesday,Lays,10,20,17,200,500.0,40.000000,12.0,850,NaN
4,Wednesday,Lays,15,20,17,300,200.0,150.000000,9.0,1350,1000.0
6,Thursday,Lays,5,20,17,100,300.0,33.333333,14.0,1550,600.0
8,Friday,Lays,15,20,17,300,100.0,300.000000,10.0,2050,700.0
10,Saturday,Lays,35,20,17,700,300.0,233.333333,3.0,2900,1100.0
12,Sunday,Lays,45,20,17,900,700.0,128.571429,1.0,4050,1900.0